name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Issue will be closed due to inactivity. Please comment if you would like to keep it open.'
          stale-pr-message: 'PR will be closed due to inactivity. Please comment if you would like to keep it open.'
          days-before-stale: 30
          operations-per-run: 100