name: Deploy Storybook to github page

on:
  push:
    branches:
      - master

jobs:
  deploy-storybook:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          registry-url: https://registry.npmjs.org/
      - name: npm install and deploy
        run: |
          npm ci
          npm run deploy-storybook -- --ci
        env:
          CI: true
          GH_TOKEN: github-orchestrated:${{ secrets.GITHUB_TOKEN }}
