name: Deploy Storybook to github page

on:
  push:
    branches:
      - master

jobs:
  deploy-storybook:
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          registry-url: https://registry.npmjs.org/
      - name: npm install and deploy
        run: |
          npm ci
          npm run deploy-storybook -- --ci
        env:
          CI: true
          GH_TOKEN: github-orchestrated:${{ secrets.GITHUB_TOKEN }}
